{ pkgs }:
{
  inherit (pkgs)
    _3mux
    act
    actionlint
    aerc
    age
    agebox
    air
    alertmanager-bot
    alertmanager-irc-relay
    align
    aliyun-cli
    amass
    amazon-ecr-credential-helper
    amfora
    antibody
    aptly
    archiver
    argo
    argocd
    arkade
    ascii-image-converter
    asciigraph
    asmfmt
    assh
    assign-lb-ip
    atlantis
    autorestic
    autospotting
    aviator
    awless
    aws-env
    aws-iam-authenticator
    aws-lambda-rie
    aws-nuke
    aws-okta
    aws-rotate-key
    aws-vault
    awsweeper
    azure-storage-azcopy
    azure-vhd-utils
    babelfish
    base16-universal-manager
    bazel-buildtools
    bazel-gazelle
    bazel-kazel
    bazel-remote
    bazelisk
    bee
    bee-unstable
    berglas
    bettercap
    bit
    blockbook
    boltbrowser
    bombadillo
    boohu
    boringssl
    bosh-cli
    bosun
    boulder
    brig
    brook
    browserpass
    browsh
    btops
    buf
    buildah-unwrapped
    buildifier
    buildkit
    buildkite-agent
    buildkite-agent-metrics
    buildkite-agent3
    buildkite-cli
    buildozer
    buildpack
    bump
    bunnyfetch
    butane
    bypass403
    c14
    caddy
    cadvisor
    calyx-vpn
    cameradar
    captive-browser
    cariddi
    cassowary
    cayley
    cdk-go
    certgraph
    certigo
    certmgr
    certmgr-selfsigned
    certstrap
    cfssl
    chamber
    changetower
    chaos
    charm
    chart-testing
    cheat
    checkip
    checkmake
    checkmate
    chezmoi
    chisel
    chopchop
    chroma
    cilium-cli
    circleci-cli
    clair
    clash
    claws
    cli53
    clickhouse-backup
    cliphist
    clipman
    cloud-nuke
    cloud-sql-proxy
    cloudbrute
    cloudflared
    cloudfoundry-cli
    cloudlist
    cloudmonkey
    clusterctl
    cni
    cni-plugin-flannel
    cni-plugins
    cockroachdb
    cod
    codesearch
    cointop
    compile-daemon
    confd
    conftest
    consul
    consul-alerts
    consul-template
    container-linux-config-transpiler
    containerd
    containerd_1_4
    containerpilot
    convoy
    cordless
    coredns
    corerad
    corgi
    corsmisc
    cosign
    coyim
    crane
    crd2pulumi
    credential-detector
    credhub-cli
    cri-o
    cri-o-unwrapped
    cri-tools
    crlfuzz
    croc
    cshatag
    csvdiff
    ctop
    cue
    curl_unix_socket
    curlie
    dalfox
    damon
    dapper
    dapr-cli
    dasel
    dashing
    datadog-agent
    datadog-process-agent
    datree
    dave
    dbmate
    dcrd
    dcrwallet
    dcs
    ddosify
    deadcode
    deepsea
    deis
    deisctl
    delve
    demoit
    dendrite
    dep
    dep2nix
    desync
    devd
    dex-oidc
    dgraph
    direnv
    diskrsync
    dismap
    distrobuilder
    dive
    dnscontrol
    dnscrypt-proxy2
    dnsname-cni
    dnsproxy
    dnstake
    dnsx
    do-agent
    docker
    docker-buildx
    docker-client
    docker-compose_2
    docker-credential-gcr
    docker-credential-helpers
    docker-distribution
    docker-edge
    docker-ls
    docker-machine
    docker-machine-hyperkit
    docker-machine-kvm
    docker-machine-kvm2
    docker-machine-xhyve
    docker-proxy
    docker-slim
    docker_20_10
    dockfmt
    dockle
    docopts
    doctl
    docui
    documize-community
    dolt
    doppler
    dorkscout
    driftctl
    drive
    drone
    drone-cli
    drone-oss
    drone-runner-docker
    drone-runner-exec
    dstask
    dstp
    duckling-proxy
    duf
    duplicacy
    dyff
    earlybird
    earthly
    easyjson
    ec2-metadata-mock
    echoip
    ecs-agent
    editorconfig-checker
    efm-langserver
    ejson
    eksctl
    element
    elfinfo
    elvish
    envconsul
    envdir
    envsubst
    erigon
    errcheck
    esbuild
    esbuild_netlify
    etcd
    etcd_3_4
    etcdctl
    evans
    evmdis
    exercism
    exoscale-cli
    expenses
    f1viewer
    faas-cli
    fac
    faraday
    ffuf
    filebeat
    filebeat6
    filebeat7
    filegive
    filtron
    fioctl
    firectl
    fission
    fits-cloudctl
    flannel
    flex-ncat
    flex-ndax
    fluxcd
    fluxctl
    fly
    flyctl
    fn-cli
    frangipanni
    frp
    frugal
    fscrypt-experimental
    fsql
    fulcio
    fwanalyzer
    fzf
    galene
    galer
    garble
    gau
    gauge
    gawp
    gb-backup
    gcrane
    gcsfuse
    gdrive
    gdu
    geek-life
    gemget
    geoipupdate
    gh
    gh-ost
    ghorg
    ghostunnel
    ghq
    ghr
    ginkgo
    git-annex-remote-b2
    git-appraise
    git-bug
    git-chglog
    git-codereview
    git-credential-gopass
    git-hound
    git-lfs
    git-lfs1
    git-sizer
    git-subtrac
    git-town
    gitaly
    gitbatch
    gitea
    github-cli
    github-commenter
    github-release
    gitjacker
    gitlab-pages
    gitlab-runner
    gitlab-shell
    gitlab-workhorse
    gitleaks
    gitty
    gjo
    glab
    glide
    gllvm
    glock
    glow
    gmailctl
    gmnitohtml
    gnatsd
    go-2fa
    go-audit
    go-bindata
    go-bindata-assetfs
    go-check
    go-chromecast
    go-containerregistry
    go-cve-search
    go-dependency-manager
    go-ethereum
    go-jira
    go-jsonnet
    go-junit-report
    go-langserver
    go-libp2p-daemon
    go-license-detector
    go-md2man
    go-migrate
    go-minimock
    go-mk
    go-mockery
    go-motion
    go-mtpfs
    go-neb
    go-org
    go-outline
    go-protobuf
    go-pup
    go-repo-root
    go-rice
    go-sct
    go-shadowsocks2
    go-swag
    go-swagger
    go-symbols
    go-task
    go-toml
    go-tools
    go-upower-notify
    go2nix
    go365
    goa
    gobetween
    gobgp
    gobgpd
    gobuster
    gocode
    gocode-gomod
    goconst
    goconvey
    gocryptfs
    gocyclo
    godef
    godns
    godu
    gofu
    gofumpt
    gogetdoc
    gogs
    gohai
    goimapnotify
    goimports
    gojsontoyaml
    gokart
    goklp
    golangci-lint
    golint
    gomacro
    gomatrix
    gomobile
    gomodifytags
    gomplate
    gomuks
    gonic
    goofys
    gopacked
    gopass
    gopass-jsonapi
    gophernotes
    gopkgs
    gopls
    gops
    gore
    goreleaser
    goreman
    goreplay
    gortr
    gosec
    gosh
    gospider
    goss
    gosu
    gotags
    gotest
    gotests
    gotestsum
    gotestwaf
    gotify-cli
    gotify-server
    gotools
    gotop
    gotty
    govc
    govendor
    govers
    gox
    grafana
    grafana-agent
    grafana-loki
    grafana_reporter
    grit
    grobi
    gron
    grpcui
    grpcurl
    grv
    grype
    gsctl
    gst
    guardian-agent
    gucci
    gvisor-containerd-shim
    gvproxy
    gx
    gx-go
    hakrawler
    harmonist
    hasmail
    hasura-cli
    hcloud
    hd-idle
    headscale
    heapster
    heartbeat
    heartbeat6
    heartbeat7
    hecate
    helm-docs
    helmfile
    helmsman
    hetzner-kube
    hey
    hilbish
    hivemind
    hockeypuck
    holo-build
    holochain-go
    hologram
    honeytrap
    hostctl
    hostess
    hound
    htmltest
    httpdump
    httplab
    httpx
    hub
    hubble
    hugo
    humioctl
    hydron
    hydroxide
    hyperledger-fabric
    hyprspace
    i3cat
    iamy
    ic-keysmith
    ical2org
    iferr
    ignite
    ijq
    img
    img-cat
    imgcrypt
    imgproxy
    impl
    ineffassign
    influxdb
    influxdb2
    infracost
    interactsh
    interfacer
    interlock
    ipfs
    ipfs-cluster
    ipfs-migrator
    ipget
    ipinfo
    ircdog
    istioctl
    jd
    jd-diff-patch
    jid
    jiq
    jmespath
    joker
    journalbeat
    journalbeat6
    journalbeat7
    jp
    json2hcl
    jsonnet-bundler
    juju
    jump
    jx
    k0sctl
    k2tf
    k6
    k9s
    kail
    kapacitor
    kapowbang
    kapp
    kappanhang
    kbfs
    kcli
    kconf
    kepubify
    kexpand
    keybase
    keybase-go
    keycard-cli
    kfctl
    kiln
    kind
    kiterunner
    kn
    ko
    kompose
    konstraint
    kontemplate
    kopia
    kops
    kops_1_20
    kops_1_21
    kops_1_22
    kpt
    kratos
    krew
    kt
    kube-aws
    kube-capacity
    kube-prompt
    kube-router
    kube-score
    kube3d
    kubeaudit
    kubebuilder
    kubecfg
    kubeconform
    kubectl-doctor
    kubectl-evict-pod
    kubectl-example
    kubectx
    kubedb-cli
    kubei
    kubeless
    kubelogin
    kubelogin-oidc
    kubeone
    kubeprompt
    kubepug
    kubernetes-controller-tools
    kubernetes-helm
    kubescape
    kubeseal
    kubesec
    kubespy
    kubeval
    kubicorn
    kuma
    kuma-cp
    kuma-dp
    kuma-experimental
    kuma-prometheus-sd
    kumactl
    kustomize
    kustomize-sops
    kustomize_3
    kuttl
    lab
    lazydocker
    lazygit
    leaps
    lefthook
    lego
    levant
    lf
    libgen-cli
    librarian-puppet-go
    librespeed-cli
    lifecycled
    lightning-loop
    lightning-pool
    lightwalletd
    ligolo-ng
    lima
    limesctl
    linkerd
    linkerd_edge
    linkerd_stable
    linuxkit
    litestream
    livedl
    livepeer
    lnch
    lnd
    lndconnect
    localtime
    loccount
    lokalise2-cli
    lxd
    mackerel-agent
    maddy
    madonctl
    mage
    magnetico
    mailhog
    maligned
    mani
    manul
    mapcidr
    marathonctl
    mark
    massren
    matrix-corporal
    matterbridge
    matterircd
    mautrix-whatsapp
    mbtileserver
    mdr
    meme
    meme-image-generator
    mesos-dns
    metabigor
    metal-cli
    metricbeat
    metricbeat6
    metricbeat7
    micro
    microplane
    minica
    miniflux
    minify
    minikube
    minio
    minio-certgen
    minio-client
    minishift
    mirrorbits
    mkcert
    mm
    mmake
    mmark
    mmv-go
    mob
    mockgen
    mod
    modd
    mole
    molly-brown
    mongodb-tools
    monsoon
    mop
    morph
    morty
    mpd-mpris
    mqtt-bench
    mtail
    mubeng
    multus-cni
    mustache-go
    mutagen
    mycorrhiza
    mynewt-newt
    naabu
    nali
    nar-serve
    nats-server
    nats-streaming-server
    nats-top
    natscli
    ncdns
    nebula
    neo-cowsay
    nerdctl
    nextdns
    nfpm
    nginx-sso
    ngrok-1
    nix-build-uncached
    nix-store-gcs-proxy
    nixops-dns
    nkeys
    nmap-formatter
    node-problem-detector
    noisetorch
    nomad
    nomad-autoscaler
    nomad-driver-podman
    nomad_1_0
    nomad_1_1
    nosqli
    notary
    noti
    notify
    nsq
    nuclei
    nwg-drawer
    nwg-menu
    oapi-codegen
    oauth2-proxy
    oauth2_proxy
    obfs4
    oci-image-tool
    oh
    oneshot
    open-policy-agent
    openring
    openshift
    opensmtpd-filter-rspamd
    opensnitch
    opentelemetry-collector
    operator-sdk
    oshka
    ossutil
    otpauth
    out-of-tree
    overmind
    owncast
    pachyderm
    packer
    packet
    packet-cli
    packet-sd
    packetbeat
    packetbeat6
    packetbeat7
    paco
    paperlike-go
    passphrase2pgp
    pbgopy
    pcstat
    pdfcpu
    peach
    pebble
    peco
    perkeep
    pet
    pg_featureserv
    pg_flame
    pg_tileserv
    pgcenter
    pgmetrics
    pgo-client
    pgweb
    phraseapp-client
    pigeon
    pistol
    pixiecore
    pkger
    platinum-searcher
    plik
    podgrab
    podman
    podman-unwrapped
    pomerium
    pond
    popeye
    powerline-go
    pprof
    prism
    prom2json
    prometheus
    prometheus-alertmanager
    prometheus-apcupsd-exporter
    prometheus-artifactory-exporter
    prometheus-aws-s3-exporter
    prometheus-bind-exporter
    prometheus-bird-exporter
    prometheus-blackbox-exporter
    prometheus-collectd-exporter
    prometheus-consul-exporter
    prometheus-dnsmasq-exporter
    prometheus-domain-exporter
    prometheus-dovecot-exporter
    prometheus-fastly-exporter
    prometheus-flow-exporter
    prometheus-fritzbox-exporter
    prometheus-gitlab-ci-pipelines-exporter
    prometheus-haproxy-exporter
    prometheus-influxdb-exporter
    prometheus-jitsi-exporter
    prometheus-json-exporter
    prometheus-keylight-exporter
    prometheus-lnd-exporter
    prometheus-mail-exporter
    prometheus-mesos-exporter
    prometheus-mikrotik-exporter
    prometheus-minio-exporter
    prometheus-modemmanager-exporter
    prometheus-mysqld-exporter
    prometheus-nextcloud-exporter
    prometheus-nginx-exporter
    prometheus-nginxlog-exporter
    prometheus-node-exporter
    prometheus-openldap-exporter
    prometheus-openvpn-exporter
    prometheus-pihole-exporter
    prometheus-postfix-exporter
    prometheus-postgres-exporter
    prometheus-process-exporter
    prometheus-pushgateway
    prometheus-rabbitmq-exporter
    prometheus-redis-exporter
    prometheus-rtl_433-exporter
    prometheus-script-exporter
    prometheus-smartctl-exporter
    prometheus-smokeping-prober
    prometheus-snmp-exporter
    prometheus-sql-exporter
    prometheus-statsd-exporter
    prometheus-surfboard-exporter
    prometheus-systemd-exporter
    prometheus-unifi-exporter
    prometheus-varnish-exporter
    promscale
    proto-contrib
    protoc-gen-doc
    protoc-gen-go
    protoc-gen-go-grpc
    protoc-gen-go-vtproto
    protoc-gen-twirp
    protoc-gen-twirp_php
    protoc-gen-twirp_swagger
    protoc-gen-twirp_typescript
    protolock
    protonmail-bridge
    prototool
    prow
    proxify
    pscale
    pufferpanel
    pup
    pwdsafety
    qbec
    qrcp
    quicktemplate
    quorum
    rakkess
    ran
    rancher
    rclone
    reflex
    reftools
    reg
    regbot
    regclient
    regctl
    regsync
    rekor-cli
    rekor-server
    remote-touchpad
    renderizer
    reposurgeon
    reproxy
    restic
    restic-rest-server
    reviewdog
    richgo
    riseup-vpn
    rmapi
    robustirc-bridge
    rootlesskit
    round
    rtsp-simple-server
    run
    runc
    s3gof3r
    s5cmd
    safe
    saml2aws
    sammler
    sampler
    scaleway-cli
    scc
    scilla
    scmpuff
    scollector
    scorecard
    sd-local
    seaweedfs
    secretscanner
    senpai
    sensu-go-agent
    sensu-go-backend
    sensu-go-cli
    senv
    serfdom
    shadowfox
    shadowsocks-v2ray-plugin
    shellhub-agent
    shellz
    shfmt
    shhgit
    shiori
    shipyard
    shopify-themekit
    sift
    sigurlx
    simplehttp2server
    singularity
    sish
    skaffold
    skate
    skopeo
    skydns
    slack-term
    slides
    smimesign
    snowcat
    snowcrash
    soft-serve
    soju
    sonobuoy
    sops
    spicetify-cli
    spicy
    spruce
    spyre
    sqls
    srtrelay
    ssb
    ssh-chat
    ssh-key-confirmer
    ssh-to-age
    ssh-to-pgp
    sshchecker
    ssm-agent
    ssmsh
    starboard
    starboard-octant-plugin
    statik
    steampipe
    step-ca
    step-cli
    stern
    storrent
    stripe-cli
    subfinder
    subjs
    sudolikeaboss
    summon
    swego
    sx-go
    syncthing
    syncthing-cli
    syncthing-discovery
    syncthing-relay
    syncthing-tray
    systemd-journal2gelf
    systrayhelper
    tailscale
    tanka
    tar2ext4
    tea
    tegola
    tektoncd-cli
    teleconsole
    telegraf
    teleport
    telepresence2
    teler
    tempo
    temporal
    tendermint
    termdbms
    terminal-parrot
    termshark
    terracognita
    terraform
    terraform-docs
    terraform-inventory
    terraform-ls
    terraform-lsp
    terraform-provider-ibm
    terraform-provider-libvirt
    terraform-provider-lxd
    terraform-provider-nixos
    terraform_0_12
    terraform_0_13
    terraform_0_14
    terraform_0_15
    terraformer
    terragrunt
    terrascan
    tewisay
    textql
    tf2pulumi
    tfk8s
    tflint
    tfsec
    tfswitch
    tgswitch
    thanos
    ticker
    tilt
    timescale-prometheus
    timescaledb-parallel-copy
    timescaledb-tune
    timew-sync-server
    tinygo
    tmsu
    todoist
    topicctl
    toxiproxy
    traefik
    traefik-certs-dumper
    traitor
    trezord
    trickster
    trillian
    trivy
    tsukae
    tty-share
    turbogit
    tut
    tychus
    tz
    ua
    uchess
    ultralist
    umoci
    unconvert
    unifi-poller
    unifiedpush-common-proxies
    unpackerr
    unused_deps
    up
    upterm
    urlhunter
    uroboros
    usql
    utahfs
    vale
    vault
    vegeta
    velero
    vend
    vendir
    verifpal
    versus
    vgo2nix
    vgrep
    victoriametrics
    viddy
    vikunja-api
    vndr
    vouch-proxy
    vsh
    vultr
    vultr-cli
    waitron
    wakatime
    wal-g
    wallutils
    wally-cli
    waypoint
    webcat
    webdav
    webhook
    websocketd
    webwormhole
    wego
    wire
    wireguard-go
    wormhole-william
    wprecon
    wrap
    writefreely
    ws
    wtf
    wuzz
    xd
    xmonad-log
    xmpp-client
    xurls
    yajsv
    yaml2json
    yeetgif
    yggdrasil
    yj
    yq-go
    ytt
    yubikey-agent
    yubikey-touch-detector
    zabbixctl
    zdns
    zfsbackup
    zgrab2
    zk
    zoekt
    zrepl
    zsh-history;
}
