name: update
on:
  workflow_dispatch:

jobs:
  inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - uses: DeterminateSystems/update-flake-lock@v3
